### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by tematres** [digitalutsc/arks-service#19]
Hi, (sorry about my english), we follow the steps but the install procedure not work :/ Here the error:
Uncaught Error: Class "Noid\\Config\\MysqlArkConf" not found in /var/www/html/test/ark/arks-service/admin/NoidLib/custom/Database.php:118\nStack

thank in advances

**Comment by kylehuynh205** [comment]
Hi, looks like the database configuration for the application is missing. You can add it as step 4 in this session: https://github.com/digitalutsc/arks-service/wiki#in-an-apache-server-for-productions-deployment

![image](https://user-images.githubusercontent.com/7862086/222800321-24203c6b-9708-4e39-b193-c3ad30c311a2.png)

**Comment by tematres** [comment]
Hi @kylehuynh205 , thank you about the answer :) We have http and MySql server wel configurated (i think :)). 
here our file:
<?php

namespace Noid\Lib\Custom;

class MysqlArkConf
{
    static public $mysql_host = 'localhost'; // host of your server
    static public $mysql_user = 'user_example'; // your MYSQL username
    static public $mysql_passwd = 'user_pass'; // your MYSQL password
    static public $mysql_dbname = 'test'; // please enter the name of database which you have just created.  
    static public $mysql_port = 3306;
    static public $path_db_backup = "/var/www/test/ark/ark-services/db/backup/"; // backup directory for database snapshot
    
}
?>
But the error persist :/ There are another config file?

thank you in advance

**Comment by tematres** [comment]
Sorry, I forguet the file content:
![image](https://user-images.githubusercontent.com/361083/229158287-2c932dd5-588d-4133-8dad-97f4bf8a51a6.png)

**Comment by kylehuynh205** [comment]
Hi @tematres , yes, with the config and modified with your server's credentials, the app should work. If there is any other issue, please let me know. Thanks.

**Comment by tematres** [comment]
Hi @kylehuynh205 , we try to run the install procedure and have this error in error.log (file not found), any idea?:

[Fri Mar 31 15:06:35.984775 2023] [proxy_fcgi:error] [pid 24633] [client 127.0.0.1:36076] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class "Noid\\Config\\MysqlArkConf" not found in /var/www/html/test/ark/arks-service/admin/NoidLib/custom/Database.php:118\nStack trace:\n#0 /var/www/html/test/ark/arks-service/admin/install.php(14): Noid\\Lib\\Custom\\Database::isInstalled()\n#1 {main}\n  thrown in /var/www/html/test/ark/arks-service/admin/NoidLib/custom/Database.php on line 118', referer: http://localhost/test/ark/arks-service/admin/

thnaks in advance

**Comment by kylehuynh205** [comment]
Hi @tematres, the error indicates the the clas MysqlArkConfig is still missing. Did you locate the file MysqlArkConf.php is at `/var/www/ark-services/config/` ?  

We also have a demo setup in a Anisible playbook to simulate the installation for this app https://github.com/digitalutsc/arks-service-playbook. in the html directory, show how the config is located as well. https://github.com/digitalutsc/arks-service-playbook/tree/master/html. I hope this can help.

**Comment by Natkeeran** [comment]
There is a new release.  This issue should be resolved.
