### ISSUE TITLE
Can't reach install page

### ISSUE THREAD

**Issue by bondjimbond** [digitalutsc/arks-service#22]
I have followed the instructions here: https://github.com/digitalutsc/arks-service/wiki#in-an-apache-server-for-productions-deployment

Set up my working LAMP stack, installed phpMyAdmin, created a database and added a config file (note: I had to create a config director as there isn't one in the repo). 

When I go to my site (https://ark-services.arcabc.ca) I get the UTSC page only, and if I try to reach https://ark-services.arcabc.ca/admin/install.php I get a 500 error.

The one thing I did which may be incorrect is that I installed into /var/www/html instead of /var/www/ark-services, but I don't believe that specific directory is hard-coded anywhere.

I am not seeing any errors logged, though I may not be looking in the right places. Any ideas where I might be going wrong?

**Comment by kylehuynh205** [comment]
Hello @bondjimbond  , my apology for taking a few days to get back to you. So in the database setup the installation documentation, I found out the name space is incorrect, which may cause the 500 error. (change to  `namespace Noid\Config;` before was namespace Noid\Config\custom). If it doesn't solve the issue, you can access the log and send me the 500 error. I can continue to debug it. Thanks. 

````
<?php

namespace Noid\Config;

class MysqlArkConf
{
    static public $mysql_host = ''; // host of your server
    static public $mysql_user = ''; // your MYSQL username
    static public $mysql_passwd = ''; // your MYSQL password
    static public $mysql_dbname = ''; // please enter the name of database which you have just created.  
    static public $mysql_port = 3306;
    static public $path_db_backup = "/var/www/ark-services/db/backup/"; // backup directory for database snapshot
    
}

````

**Comment by bondjimbond** [comment]
Thanks, Kyle. That did turn out to be the problem. 

I also had other 500 errors after I successfully got through this step, but I was able to solve them -- it turns out that the default version of PHP installed when I ran the php install command was 7.2, but it won't work without 7.4.3. After updating, things are working OK.
