### ISSUE TITLE
Documentation on NAAN

### ISSUE THREAD

**Issue by bondjimbond** [digitalutsc/arks-service#23]
The software requires a NAAN, but does not mention how to get one. 

I found [this page](https://arks.org/about/ark-naans-and-systems/) linking to a [form to request a NAAN](https://docs.google.com/forms/d/e/1FAIpQLSfd1CX6idwLB47g8OGKUG654auV8IU8yI7DAs61cXGOoFDn0g/viewform?c=0&w=1); is this the appropriate path? If so, could it be added to the install/setup documentation?

**Comment by kylehuynh205** [comment]
you can visit https://arks.org/about/getting-started-implementing-arks/ for more information to request a NAAN, 

there is a form https://docs.google.com/forms/d/e/1FAIpQLSfd1CX6idwLB47g8OGKUG654auV8IU8yI7DAs61cXGOoFDn0g/viewform?c=0&w=1 to fill in.
