### ISSUE TITLE
Documentation: Meanings of fields

### ISSUE THREAD

**Issue by bondjimbond** [digitalutsc/arks-service#24]
The [Usage documentation](https://github.com/digitalutsc/arks-service/wiki#usage) does not describe how to use all necessary fields when creating collections. Three elements that need some elaboration:

- Name Assigning Authority Number (NAAN) - how to get one (see #23)
- Name Assigning Authority - what this means, how to find it, how to fill out the field
- Term (short, medium, long) - What this means, how to choose, what effect this has on your IDs

Details here would be much appreciated, and make setup easier.

**Comment by kylehuynh205** [comment]
There is a documentation from the NOID library https://metacpan.org/dist/Noid/view/noid

* NAA: "The NAA argument is the character string equivalent for the NAAN; for example, 13960 corresponds to the NAA, "archive.org". The SubNAA argument is also a character string, but is a locally determined and possibly structured subauthority string (e.g., "oac", "ucb/dpg", "practice_area") that is not globally registered."
* Term: "The Term declares whether the identifiers are intended to be "long", "medium" (the default), or "short". A short term identifier minter is the only one that will re-mint identifiers after the namespace is exhausted, simply returning the oldest previously minted identifier. As mentioned earlier, however, some namespaces are unbounded and never run out of identifiers. If Term is "long", the arguments NAAN, NAA, and SubNAA are required, and all minted identifiers will be returned with the NAAN and a "/" prepended to them. The NAAN is a namespace identifier and should be a globally unique Name Assigning Authority (NAA) number. Apply for one by email to ark@cdlib.org, or for testing purposes, use "00000" as a non-unique NAAN."

**Comment by bondjimbond** [comment]
Thanks, Kyle. Could this information and the NAAN request form be added to the documentation?

**Comment by kylehuynh205** [comment]
the information was added to the documentation.
